### ISSUE TITLE
Add 20/8/2021 data

### ISSUE THREAD

**Issue by ashraf-fuad** [HKL84/Malaysia-Covid19-Updated-Daily-Based-on-KKM-Data-#1]
Please add the update for 20/8

2021/08/20,2257,1882,41,12,10,9531,9463,195,65,108

**Comment by HKL84** [comment]
Hi. Unfortunately the government didnt publish this info on that day so i cant add it in.

**Comment by ashraf-fuad** [comment]
These are the image uploaded into the cprc kkm telegram group on 20/8

**Comment by HKL84** [comment]
Yes. I extract from here too. But on that day the data is not published. If you can find the image you can send the link to me.

**Comment by ashraf-fuad** [comment]
https://covid-19.moh.gov.my/terkini/2021/08/situasi-terkini-covid-19-di-malaysia-20082021

**Comment by HKL84** [comment]
I see. This figure doesnt give the exact number of cases for vaccinated and non vaccinated individual. But I can back calculate the number based on the percentage. 

The accuracy will be lower but i guess it will be better than missing data then. OK, the data are added.

**Comment by ashraf-fuad** [comment]
Thanks.
